/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'matteo' at '18/05/16 11:08' with Gradle 2.13
 *
 * @author matteo, @date 18/05/16 11:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
